apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  containers:
    - name: foo
      command: [ go, run, ./internal/server ]
      env:
        - name: PORT
          value: "8080"
      readinessProbe:
        initialDelaySeconds: 10
        httpGet:
          port: 8080
    - name: bar
      command: [ go, run, ./internal/server ]
      env:
        - name: PORT
          value: "9090"
      readinessProbe:
        initialDelaySeconds: 10
        httpGet:
          port: 9090

