apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  initContainers:
    - name: init
      command: [ sleep, "3" ]
  containers:
    # no image? this is a host process
    - name: foo
      command: [ go, run, ./demo/foo ]
      livenessProbe:
        failureThreshold: 3
        tcpSocket:
          port: 8080
      # no image? this is a host process
    - name: bar
      command: [ go, run, ./demo/bar ]
      env:
        - name: PORT
          value: "9090"
      readinessProbe:
        httpGet:
          port: 9090
    # conventional image? run in Docker
    - name: baz
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 7070
      readinessProbe:
        httpGet:
          port: 7070
    # path image? build and run in Docker
    - name: qux
      image: ./demo/qux/Dockerfile
      ports:
        - containerPort: 80
          hostPort: 6060
      readinessProbe:
        httpGet:
          port: 6060