apiVersion: v1
kind: Pod
metadata:
  name: kit
spec:
  containers:
  - command:
    - go
    - run
    - ./demo/foo
    livenessProbe:
      tcpSocket:
        port: 8080
    name: foo
  - command:
    - go
    - run
    - ./demo/bar
    env:
    - name: PORT
      value: "9090"
    name: bar
    readinessProbe:
      httpGet:
        port: 9090
  - image: httpd
    name: baz
    ports:
    - containerPort: 80
      hostPort: 7070
    readinessProbe:
      httpGet:
        port: 7070
  - image: ./demo/qux
    name: qux
    ports:
    - containerPort: 80
      hostPort: 6060
    readinessProbe:
      httpGet:
        port: 6060
  initContainers:
  - command:
    - sleep
    - "1"
    name: init
status: {}
